### ISSUE TITLE
Integration test bytes.hurl is not syntaxically correct

### ISSUE THREAD

**Issue by jcamiel** [fabricereix/hurl#4]
Integration test bytes.hurl is not syntactically correct, there must be at least one assert

https://github.com/fabricereix/hurl/blob/8891e710bcced7977a463e889ac0dd0a8409bf8d/integration/tests/bytes.hurl#L4-L6 

Grammar:

```
asserts-section = lt*
  sp* "[Asserts]" lt
  assert+
```

**Comment by fabricereix** [comment]
Grammar updated
allow empty section
